### ISSUE TITLE
Just experiment with knife-kvm 

### ISSUE THREAD

**Issue by gravyflex** [chef/knife-kvm#11]
I'm Just experimenting with knife-kvm, any ideas how to fix?
```
knife kvm
/usr/lib/ruby/2.3.0/rubygems/specification.rb:2286:in `raise_if_conflicts': Unable to activate knife-kvm-0.0.1, because chef-13.0.118 conflicts with chef (~> 12.0) (Gem::ConflictError)
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1407:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/knife-kvm-0.0.1/lib/chef/knife/kvm_vm_list.rb:19:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/knife/core/subcommand_loader.rb:85:in `load'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/knife/core/subcommand_loader.rb:85:in `block in load_commands'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/knife/core/subcommand_loader.rb:85:in `each'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/knife/core/subcommand_loader.rb:85:in `load_commands'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/knife/core/subcommand_loader.rb:95:in `load_command'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/knife.rb:214:in `run'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/lib/chef/application/knife.rb:156:in `run'
	from /var/lib/gems/2.3.0/gems/chef-13.0.118/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:23:in `load'
	from /usr/local/bin/knife:23:in `<main>'
```

**Comment by scotthain** [comment]
knife-kvm hasn't been updated to work with chef-13 yet - I would recommend using bundler and do:
```
bundle install
bundle exec knife <command>
```
